language: java

env:
  global:
    - secure: "Muz5Ii7rsZeJsBuwQF5uE5VRD0DuRk4ZUz1NjE6M6kUy29JpJPkN4bMCTUmO\n6QVrFY00ikiRtTZyrYYOLb1CQsnBhJwiwN84+rFCCkT6zgcV8wMqQvQv4TqD\n3h40sqPvT8OhxpxFqB1oITCOOx9GekOUST3k+6RrxsSTs9kwnPc="
    - secure: "Q//B5s7JXDAKnS1JVwumUngrsXWtnxjjv4wO32l8xLORnCPaPYU8aPM/pr7/\niAjNgqdzfpQ0BpN3kl2xcud4UG843yIAy/Ld1q4dRY8XYm7+JcRBL0am4YdW\n3HyAiwJvbu5ou0UK1Oo5uqdOpJP/lZt+O/UexQ1dwoUkgKKwjl0="
    
after_success:
  - python travis/addServer.py
  - mvn clean deploy --settings ~/.m2/mySettings.xml